# Generated by Django 4.1.7 on 2023-03-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='dividend',
            new_name='change',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='ma200',
            new_name='mrkt_cap',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='ma50',
            new_name='vol',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='pe',
        ),
        migrations.AddField(
            model_name='asset',
            name='coin_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='name',
            field=models.CharField(default=1, max_length=75),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(max_length=75),
        ),
    ]
